CATALOGUE = [
    ("Doom", "fps", "Un marine combat les demons sur Mars.", 1993),
    ("Doom II", "fps", "Une nouvelle invasion demoniaque menace la Terre.", 1994),
    ("Quake", "fps", "Un combattant affronte les forces de Strogg.", 1996),
    ("Half-Life", "fps", "Gordon Freeman tente de survivre a un incident scientifique.", 1998),
    ("Counter-Strike", "fps", "Deux equipes s'affrontent dans des missions tactiques.", 2000),
    ("Halo: Combat Evolved", "fps", "Le Master Chief decouvre un anneau alien.", 2001),
    ("Call of Duty 4: Modern Warfare", "fps", "Des soldats menent des operations modernes.", 2007),
    ("Borderlands 2", "fps", "Des chasseurs de l'Arche explorent Pandora.", 2012),
    ("Overwatch", "fps", "Des heros aux roles varies combattent en equipe.", 2016),
    ("DOOM Eternal", "fps", "Le Doom Slayer poursuit son combat contre l'enfer.", 2020),
    ("Baldur's Gate", "rpg", "Une aventure de role dans les Royaumes oublies.", 1998),
    ("Planescape: Torment", "rpg", "Un immortel cherche a comprendre son passe.", 1999),
    ("Diablo II", "rpg", "Des heros affrontent les seigneurs des Enfers.", 2000),
    ("The Elder Scrolls III: Morrowind", "rpg", "Un elu explore l'ile volcanique de Vvardenfell.", 2002),
    ("Star Wars: Knights of the Old Republic", "rpg", "Un Jedi choisit son destin dans la galaxie.", 2003),
    ("Mass Effect", "rpg", "Le commandant Shepard rassemble un equipage contre les Moissonneurs.", 2007),
    ("The Witcher 3: Wild Hunt", "rpg", "Geralt recherche Ciri dans un monde en guerre.", 2015),
    ("Dark Souls III", "rpg", "Un Morteflamme explore un royaume en ruines.", 2016),
    ("Divinity: Original Sin 2", "rpg", "Des Sourciers s'echappent d'une colonie de Magisters.", 2017),
    ("Elden Ring", "rpg", "Un Sans-eclat parcourt l'Entre-terre pour devenir Seigneur d'Elden.", 2022),
    ("Dune II", "rts", "Les maisons Atreides, Harkonnen et Ordos se disputent Arrakis.", 1992),
    ("Warcraft II: Tides of Darkness", "rts", "Humains et orcs se livrent une guerre maritime.", 1995),
    ("Command & Conquer: Red Alert", "rts", "Les Allies et les Sovietiques s'affrontent dans une histoire alternative.", 1996),
    ("Age of Empires", "rts", "Des civilisations evoluent de l'Antiquite a l'age du fer.", 1997),
    ("StarCraft", "rts", "Terrans, Zergs et Protoss luttent pour le secteur Koprulu.", 1998),
    ("Warcraft III: Reign of Chaos", "rts", "Des heros conduisent leurs factions face a la Legion ardente.", 2002),
    ("Company of Heroes", "rts", "Des troupes alliees combattent en Europe pendant la Seconde Guerre mondiale.", 2006),
    ("Supreme Commander", "rts", "Trois factions utilisent des armees futuristes a grande echelle.", 2007),
    ("StarCraft II: Wings of Liberty", "rts", "Jim Raynor mene une rebellion contre le Dominion.", 2010),
    ("Age of Empires IV", "rts", "Des civilisations historiques s'affrontent au Moyen Age.", 2021),
    ("SimCity 2000", "gestion", "Le joueur construit et administre une ville.", 1993),
    ("Theme Hospital", "gestion", "Des hopitaux sont construits et geres avec humour.", 1997),
    ("RollerCoaster Tycoon", "gestion", "Un parc d'attractions est construit et exploite.", 1999),
    ("The Sims", "gestion", "Le quotidien de personnages virtuels est organise par le joueur.", 2000),
    ("Zoo Tycoon", "gestion", "Un zoo est amenage pour accueillir visiteurs et animaux.", 2001),
    ("Prison Architect", "gestion", "Une prison est construite et administree.", 2015),
    ("Cities: Skylines", "gestion", "Une metropole est planifiee et developpee.", 2015),
    ("Planet Coaster", "gestion", "Un parc a theme est cree et gere.", 2016),
    ("Two Point Hospital", "gestion", "Un reseau d'hopitaux aux maladies insolites est gere.", 2018),
    ("Planet Zoo", "gestion", "Un parc zoologique est concu et entretenu.", 2019),
]

USERS = [
    
]